### ISSUE TITLE
Reconstruct `MinosModel` dinamically from avro_data and avro_schema

### ISSUE THREAD

**Issue by vladyslav-fenchak** [Clariteia/minos_microservice_common#301] opened 2021-06-03 16:08 UTC
Since right now what we get from the bytes is only the avro_data
And to do this we will also need to get the avro_schema (to later try to rebuild the class dynamically).

**Comment by garciparedes** [comment] 2021-06-14 13:39
Closing as it's a duplicate of https://github.com/Clariteia/minos_microservice_common/issues/309

**Closed by garciparedes** 2021-06-14 13:39 UTC
Labels: duplicate, enhancement
